-- Seed des 70 compétences prédéfinies (is_predefined=TRUE, created_by=NULL)
-- Garde d'idempotence : on repart d'un état propre côté prédéfinies.
DELETE FROM competences WHERE is_predefined = TRUE;

-- ===== RUNNING (10) =====
INSERT INTO competences (nom, description_courte, bullets, sports, categorie, prompt_base, is_predefined) VALUES
('Méthode Norvégienne','Double seuil contrôlé au lactate avec gros volume sub-LT2.',
 ARRAY['Lactate sanguin comme marqueur principal d''intensité','Doubles séances seuil dans la semaine (matin/soir)','Volume élevé à intensité modérée privilégié','Récupération active non négociable entre séances dures'],
 ARRAY['running'],'methodologie',
 '[Philosophie] Maximiser le volume de qualité au seuil lactique en restant sous le seuil 2. Le lactate sanguin est le marqueur d''intensité principal, pas la FC ni l''allure. Ne jamais accumuler trop de lactate. [Règles] Structurer la semaine autour de 2 séances clés au seuil, idéalement en doubles séances. Cibler 60-90 min de travail au seuil par semaine, lactate entre 2 et 4 mmol/L. Volume hebdomadaire élevé majoritairement aérobie modéré. [Exclusions] Pas de VO2max courte et explosive. Pas de tempo isolé sans contrôle lactate. Pas d''intensité maximale sans récupération substantielle. [Adaptations] En compétition courte, accepter ponctuellement de l''allure compétition. Sans lactatemètre, piloter à la FC sub-seuil et au ressenti contrôlé.',
 TRUE),
('Polarisation','Distribution bimodale 80/20 entre basse et haute intensité.',
 ARRAY['Distribution 80% faible intensité / 20% haute intensité','Zone intermédiaire (tempo, seuil) bannie','Maximisation des extrêmes d''intensité','Jours faciles vraiment faciles, jours durs vraiment durs'],
 ARRAY['running'],'methodologie',
 '[Philosophie] Sortir du no man''s land de l''intensité modérée. Le facile doit être très facile pour que le dur soit vraiment dur. Distribution bimodale stricte. [Règles] 80% du volume sous LT1, 20% au-dessus de LT2, maximum 5% en zone intermédiaire. Une à deux séances haute intensité par semaine (VO2max, intervalles courts). Le reste en endurance fondamentale. [Exclusions] Pas de tempo. Pas de séance au seuil prolongée. Pas de séance modérée longue. Pas de fartlek dérivant en zone grise. [Adaptations] En préparation d''épreuves longues, accepter du travail à allure marathon. Transition progressive sur 4-6 semaines depuis une approche seuil.',
 TRUE),
('Pyramidal','Distribution dégressive Z1 > Z2 > Z3, base aérobie large.',
 ARRAY['Volume décroissant des zones basses vers hautes','Tempo et seuil intégrés progressivement','Base aérobie dominante','Sommet haute intensité réduit mais présent'],
 ARRAY['running'],'methodologie',
 '[Philosophie] La zone intermédiaire (tempo, seuil) a une vraie valeur — pas de raison de l''éviter. Distribution en pyramide : large à la base, fine au sommet. [Règles] Environ 75% du volume en endurance fondamentale, 20% en zone modérée à seuil, 5% en très haute intensité. Intégrer 1-2 séances de tempo ou seuil par semaine. Séance longue avec progression en allure possible. [Exclusions] Pas de polarisation stricte qui vide la zone intermédiaire. Pas de séance exclusivement intense sans base aérobie suffisante. [Adaptations] Possibilité de glisser vers le polarisé en fin de cycle. En base hivernale, monter la part Z1-Z2 jusqu''à 85%.',
 TRUE),
('Méthode Lydiard','Base aérobie longue suivie d''une montée d''intensité tardive.',
 ARRAY['Phase de base aérobie de 3 à 6 mois','Course longue hebdomadaire prioritaire','Hill training comme transition vers la vitesse','Périodisation linéaire stricte vers le pic'],
 ARRAY['running'],'methodologie',
 '[Philosophie] Les kilomètres font les champions. Une grande base aérobie est la condition de toute performance ultérieure. L''intensité vient tard et se construit sur cette base. [Règles] Phase de base longue (12-24 semaines) dominée par l''endurance facile. Course longue dominicale obligatoire et progressive. Phase de transition avec hill training avant toute intensité piste. Affûtage final court mais intense. [Exclusions] Pas d''intervalles VO2max en phase de base. Pas de tempo intense avant la phase d''intensité. Pas de raccourci sur la durée de la base. [Adaptations] Pour un 5km, la phase d''intensité peut être plus marquée. Pour un marathon, la base peut s''étendre à 6 mois.',
 TRUE),
('Méthode Daniels (VDOT)','Allures d''entraînement calculées à partir du VDOT individuel.',
 ARRAY['Allures basées sur le VDOT (performance récente)','Cinq types de séances codifiés : E, M, T, I, R','Volume d''intervalles plafonné par sécurité','Approche scientifique et mesurable'],
 ARRAY['running'],'methodologie',
 '[Philosophie] Courir aussi facile que possible pour le bénéfice maximal. Chaque allure a un objectif physiologique précis. Le VDOT prédit ce qui est optimal et possible. [Règles] Toutes les allures calculées à partir du VDOT actuel. Cinq types : Easy, Marathon, Threshold, Intervals, Repetitions. Volume hebdomadaire d''intervalles plafonné selon le niveau. Périodisation en 4 phases. [Exclusions] Pas de séances à l''instinct sans cible d''allure. Pas de mélange anarchique des intensités dans une même séance. [Adaptations] Recalculer le VDOT toutes les 4-6 semaines avec une performance récente. Sans course, utiliser un test 3000m ou un effort soutenu de référence.',
 TRUE),
('MAF (Maffetone)','Endurance aérobie pure plafonnée à 180 moins l''âge.',
 ARRAY['Plafond FC strict (180 moins l''âge, ajusté)','Aucune intensité haute pendant la base','Test MAF régulier pour mesurer la progression','Approche holistique : entraînement + nutrition + stress'],
 ARRAY['running'],'methodologie',
 '[Philosophie] Maximiser la fonction aérobie et l''oxydation des lipides. La santé d''abord, la performance ensuite. L''intensité doit être méritée par une base solide. [Règles] Plafond FC strict 180 - âge (ajustements selon historique). Toutes les séances sous ce plafond. Test MAF mensuel pour suivre la progression. Phase de base de plusieurs mois avant toute réintroduction d''intensité. [Exclusions] Pas d''intervalles. Pas de tempo. Pas de séance dépassant le plafond MAF. Pas de un peu plus dur pour suivre un groupe. [Adaptations] Au plateau aérobie (test MAF stagnant), réintroduire prudemment de l''intensité courte. Le retour à MAF strict reste l''ancre par défaut.',
 TRUE),
('Méthode Canova','Extension de la durée à l''allure de course objectif.',
 ARRAY['Progression Général → Spécial → Spécifique','Volume à allure cible (90-110%) croissant','Special Blocks : doubles séances spécifiques','Approche élite, demande une grosse base'],
 ARRAY['running'],'methodologie',
 '[Philosophie] Étendre la durée pendant laquelle on tient l''allure cible. L''entraînement devient progressivement plus spécifique à l''allure objectif. [Règles] Trois phases : General, Special, Specific. Cibler 90-110% de l''allure cible dans les séances spécifiques. Special Blocks : deux séances à allure spécifique dans la journée. Volume de stress spécifique croissant vers la compétition. [Exclusions] Pas de longue sortie lente non spécifique tardivement. Pas d''intervalles trop rapides éloignés de l''allure cible en phase spécifique. Pas applicable à un débutant. [Adaptations] Demande une base aérobie large préalable. Adapter la durée des Special Blocks au niveau (élite 2h, amateur avancé 1h).',
 TRUE),
('Méthode Kényane','Haut volume à allure facile dominante, fartlek collectif.',
 ARRAY['Volume hebdomadaire très élevé','Majorité des séances très faciles','Fartlek de groupe et intervalles intenses','Altitude et consistance prioritaires'],
 ARRAY['running'],'methodologie',
 '[Philosophie] Volume avant tout, mais à allure majoritairement très facile. La qualité émerge de la quantité et de la consistance. Les séances dures se font en groupe pour pousser au-delà du confort. [Règles] Volume hebdomadaire élevé pour le niveau. 80-90% des séances en endurance très facile. 2-3 séances dures : fartlek collectif, intervalles piste, sortie progressive. Récupération sacrée entre séances dures. [Exclusions] Pas de tempo formel isolé. Pas de séance moyenne — soit très facile, soit très dure. Pas de plan rigide jour par jour. [Adaptations] Sans altitude, simuler par du volume soutenu et de la consistance. Sans groupe, augmenter la précision des objectifs d''allure.',
 TRUE),
('Méthode Igloi','Intervalles courts à effort contrôlé, jamais à fond, au ressenti.',
 ARRAY['Grands volumes d''intervalles courts (100-400m)','Effort contrôlé, jamais à 100%','Récupérations actives en trottinement','Pas de plan figé, ajustement quotidien'],
 ARRAY['running'],'methodologie',
 '[Philosophie] La forme de course et le recrutement de fibres variées priment. L''intervalle est l''outil principal mais jamais à fond — l''effort contrôlé permet d''accumuler du volume de qualité. [Règles] Séances quasi exclusivement en intervalles courts (100 à 400m), organisées en sets et sub-sets. Effort contrôlé, jamais maximal. Récupérations actives en trottinement lent. Volume d''intervalles élevé. [Exclusions] Pas d''intervalles à 100%. Pas de longue sortie traditionnelle prolongée. Pas de plan écrit à l''avance — ajustement séance par séance. [Adaptations] Pour un athlète seul, structurer en patterns prédéfinis mais autoriser l''ajustement du volume au ressenti. Garder l''effort contrôlé sacré.',
 TRUE),
('80/20 (Fitzgerald)','Polarisation accessible pour amateurs, plans clés en main.',
 ARRAY['80% du volume facile, 20% dur','Cinq zones simples basées sur la FC','Vulgarisation de la recherche de Seiler','Accessible aux coureurs amateurs'],
 ARRAY['running'],'methodologie',
 '[Philosophie] Run slow to run fast. La règle 80/20 simplifie la polarisation pour les amateurs : la plupart s''entraînent trop dur trop souvent, ce qui bloque la progression. [Règles] 80% du volume en zones 1-2 (facile à modéré-facile), 20% en zones 4-5 (dur à très dur). Système à 5 zones simplifiées, mesure à la FC. Plans hebdomadaires avec une à deux séances dures. [Exclusions] Pas de séance modérée prolongée en zone 3. Pas de juste un peu plus vite sur les sorties faciles. [Adaptations] Pour les débutants, démarrer à 90/10 et tendre vers 80/20. Pour les avancés, possibilité d''aller à 75/25 en affûtage.',
 TRUE);

-- ===== TRAIL (6) =====
INSERT INTO competences (nom, description_courte, bullets, sports, categorie, prompt_base, is_predefined) VALUES
('Vertical Kilometer (VK)','Spécialisation sur montées raides courtes et explosives.',
 ARRAY['Focus puissance et économie en montée pure','Travail en côte raide (>15% de pente)','Force-vitesse en montée prioritaire','Volume modéré, intensité montante élevée'],
 ARRAY['trail'],'methodologie',
 '[Philosophie] Maximiser la puissance et l''économie en montée. Le VK c''est sauter haut plutôt que loin ; la grip prime sur l''amorti. [Règles] Séances spécifiques en côte raide (>15%) plusieurs fois par semaine. Renforcement spécifique (squat, presse, step-ups). Intervalles uphill courts et puissants. Travail des bâtons si utilisés. Périodisation force → endurance musculaire → vitesse montante. [Exclusions] Pas de gros volume à plat. Pas de longues sorties roulantes. Pas de descente technique (sauf formats enchaînés). [Adaptations] Sans côtes raides, utiliser tapis incliné, Stairmaster ou montées d''immeubles. Adapter la force au niveau.',
 TRUE),
('Skyrunning','Course en haute montagne avec dénivelé extrême et technicité.',
 ARRAY['Puissance de grimpe et technique de descente','Adaptation à l''altitude et au terrain technique','Endurance musculaire prolongée','Distances 20-50 km avec D+/D- extrêmes'],
 ARRAY['trail'],'methodologie',
 '[Philosophie] Combiner puissance, technicité et endurance pour la haute montagne. La performance dépend autant de la grimpe que de la maîtrise de la descente technique. [Règles] Trois piliers : hill sprints, endurance musculaire, force descente. Séances dédiées en descente technique (proprioception, appuis). Intervalles uphill et downhill. Sorties longues à fort D+. [Exclusions] Pas d''entraînement plat exclusif. Pas de négligence de la descente. Pas de focus pur vitesse sans dénivelé. [Adaptations] Sans haute montagne, intégrer du dénivelé via collines répétées et sentiers techniques. Stages en altitude si possible avant compétition.',
 TRUE),
('Ultra-endurance','Préparation à des courses longues (>50 km) avec gros volume.',
 ARRAY['Volume hebdomadaire très élevé','Sorties longues 4-8h régulières','Faible intensité dominante','Marche rapide intégrée comme compétence'],
 ARRAY['trail'],'methodologie',
 '[Philosophie] Construire la durabilité et la résistance à la fatigue sur des durées extrêmes. Courir sur jambes fatiguées est une compétence. Le mental, le sommeil et la nutrition sont des leviers majeurs. [Règles] Volume hebdomadaire élevé. Sorties longues de 4 à 8h selon la phase. Back-to-back le week-end. Majorité du volume en endurance facile. Power hiking entraîné spécifiquement. Simulations nocturnes et nutrition réelle de course. [Exclusions] Pas de gros volume d''intensité. Pas de focus VO2max. Pas d''absence de longues sorties même en intersaison. [Adaptations] 50 km : 16-20 semaines. 100 miles : 24-30 semaines. Adapter la durée des back-to-back au niveau.',
 TRUE),
('Aérobie + Endurance musculaire','Approche Uphill Athlete : moteur aérobie + force périodisée.',
 ARRAY['Trois piliers : aérobie, force, endurance musculaire','Piloté par l''écart entre seuils aérobie et anaérobie','Portage lesté en montée raide (hypergravity)','Endurance musculaire introduite tardivement'],
 ARRAY['trail'],'methodologie',
 '[Philosophie] La performance en montagne repose sur un gros moteur aérobie, une force générale et spécifique, et une endurance musculaire résistant à la fatigue prolongée. [Règles] Base aérobie + force générale, puis force maximale, puis endurance de force, puis endurance musculaire spécifique introduite uniquement quand l''écart AeT-AnT est <10%. Portage lesté en montée raide. Deload avec volume réduit jusqu''à 50%. [Exclusions] Ne jamais remplacer le volume aérobie par de la ME. Pas d''ME avant une base solide. Pas de focus pur intensité sans force. [Adaptations] Si l''écart AeT-AnT reste >10%, prolonger la base. Sans salle, remplacer la force par du portage lesté en escaliers.',
 TRUE),
('Polarisation Trail','Distribution polarisée adaptée au trail avec gestion du dénivelé.',
 ARRAY['Distribution 80/20 gérée par le temps en zone','Le D+ remplace partiellement l''intensité','Gros volume en endurance facile','Séances qualité 1-2 fois par semaine'],
 ARRAY['trail'],'methodologie',
 '[Philosophie] Appliquer la polarisation au trail en tenant compte du fait que le dénivelé gonfle l''intensité cachée. Une sortie facile à 1000 m D+ n''équivaut pas à du plat. [Règles] 80/20 mesurée par le temps en zone plutôt que par la distance. 80% sous LT1, 20% au-dessus de LT2. Les sorties à fort D+ comptent comme intensité partielle. Séances qualité 1-2 fois par semaine, calées sur le terrain. [Exclusions] Pas de tempo prolongé en zone modérée. Pas de groupe courant à allure unique. [Adaptations] En préparation vallonnée, accepter du travail à allure compétition. Possibilité de glisser pyramidal → polarisé en fin de cycle.',
 TRUE),
('Minimaliste','Faible volume, focus consistance, outils alternatifs au D+.',
 ARRAY['Volume hebdomadaire modéré','Substitution du D+ (tapis incliné, Stairmaster)','1 séance hill-replacement + 1 force + 1 long run','Consistance prioritaire sur le volume'],
 ARRAY['trail'],'methodologie',
 '[Philosophie] Pour les athlètes contraints en temps ou en accès terrain. La consistance bat les grosses séances ; on substitue intelligemment ce qui manque. [Règles] Volume modéré axé consistance. Structure : 1 séance hill replacement (tapis incliné, Stairmaster, escaliers), 1 séance de force, 1 long run progressif, le reste en endurance facile. Progression mesurée par tests fixes. [Exclusions] Pas de quête du volume élite si la vie ne le permet pas. Pas de sortie de 6h en semaine. Pas adapté aux ultras très longs. [Adaptations] Si montagne ponctuelle possible (week-end mensuel), prioriser ces sorties pour le D+ réel. Insuffisant seul pour l''ultra haut de gamme.',
 TRUE);

-- ===== CYCLISME (7) =====
INSERT INTO competences (nom, description_courte, bullets, sports, categorie, prompt_base, is_predefined) VALUES
('Polarisée','Distribution bimodale 80/20 pilotée à la puissance.',
 ARRAY['80% en zone 2, 20% au-dessus du seuil','Zone tempo/sweet spot évitée','Pilotage à la puissance (zones de Coggan)','Une à deux séances haute intensité par semaine'],
 ARRAY['cyclisme'],'methodologie',
 '[Philosophie] Maximiser l''adaptation en séparant nettement le facile et le dur. Le tempo prolongé use sans le rendement des extrêmes. [Règles] 80% du volume en zone 2 (endurance), 20% au-dessus du seuil (VO2max, anaérobie). Séances clés : intervalles 4-5 min à VO2max, ou efforts courts répétés. Le reste en endurance à puissance basse stable. Pilotage à la puissance. [Exclusions] Pas de sweet spot prolongé. Pas de tempo continu. Pas de sortie à intensité moyenne dérivante. [Adaptations] En time-crunch, glisser vers plus d''intensité. Avant un objectif vallonné, intégrer des efforts spécifiques à la durée des cols.',
 TRUE),
('Sweet Spot Training','Travail intensif à 88-94% du FTP pour un ratio rendement/temps optimal.',
 ARRAY['Intensité 88-94% du FTP','Excellent ratio gains/temps investi','Volume de qualité élevé en zone sweet spot','Idéal pour cyclistes contraints en temps'],
 ARRAY['cyclisme'],'methodologie',
 '[Philosophie] Le sweet spot offre le meilleur compromis entre stimulus et récupération : presque autant de gains qu''au seuil pour moins de fatigue. [Règles] Séances clés à 88-94% du FTP, en blocs de 8 à 30 min. Plusieurs séances sweet spot par semaine possible. Endurance de base en complément. Progression par allongement de la durée totale en sweet spot. [Exclusions] Pas de polarisation stricte qui vide la zone intermédiaire. Pas de surdose de VO2max au détriment du sweet spot. [Adaptations] En approche de compétition, ajouter du travail au seuil et VO2max. Pour les gros volumes, baisser la fréquence sweet spot pour préserver la fraîcheur.',
 TRUE),
('Pyramidale','Distribution dégressive de l''endurance vers l''intensité.',
 ARRAY['Base d''endurance large, sommet intense réduit','Tempo et seuil intégrés modérément','Transition naturelle vers la polarisation','Pilotage puissance multi-zones'],
 ARRAY['cyclisme'],'methodologie',
 '[Philosophie] Construire en pyramide : beaucoup d''endurance, du seuil en quantité raisonnable, peu de très haute intensité. La zone intermédiaire a sa place. [Règles] ~75% en endurance (zone 2), ~20% tempo/seuil, ~5% VO2max et plus. Une séance seuil et une séance endurance longue par semaine. Progression vers plus d''intensité en fin de cycle. [Exclusions] Pas de polarisation stricte en début de préparation. Pas de surcharge VO2max précoce. [Adaptations] Glisser vers polarisé à l''approche de la compétition. En base hivernale, augmenter la part endurance jusqu''à 85%.',
 TRUE),
('Friel (linéaire)','Périodisation linéaire classique base → build → peak.',
 ARRAY['Progression Base → Build → Peak → Race','Volume d''abord, intensité ensuite','Semaines de récupération planifiées (3:1)','Pilotage par CTL/ATL/TSB'],
 ARRAY['cyclisme'],'periodisation',
 '[Philosophie] Construire la forme par étapes successives : d''abord le volume et l''aérobie, puis l''intensité spécifique, puis l''affûtage. La progressivité prévient le surmenage. [Règles] Phases Base (volume, technique), Build (intensité spécifique), Peak (affûtage), Race. Cycles de 3 semaines de charge + 1 de récupération. Suivi de la charge via CTL/ATL/TSB. [Exclusions] Pas d''intensité maximale en phase de base. Pas de volume écrasant en phase de peak. Pas de saut d''une phase. [Adaptations] Raccourcir Base pour un objectif rapproché. Pour un athlète expérimenté, blocs plus courts et plus denses.',
 TRUE),
('Périodisation par blocs (Rønnestad)','Blocs concentrés de VO2max suivis de récupération/endurance.',
 ARRAY['Blocs concentrés de séances VO2max','Alternance bloc dur / bloc allégé','Stimulus dense puis assimilation','Efficace pour cyclistes déjà entraînés'],
 ARRAY['cyclisme'],'periodisation',
 '[Philosophie] Concentrer un fort stimulus VO2max sur quelques jours déclenche une supercompensation supérieure à une répartition uniforme. [Règles] Bloc de 5 à 7 jours avec plusieurs séances VO2max rapprochées, suivi d''un bloc d''endurance/récupération de durée similaire. Intervalles longs (3-8 min) à haute intensité. Suivi rigoureux de la fraîcheur. [Exclusions] Pas pour un débutant sans base. Pas d''enchaînement de blocs durs sans assimilation. Pas de VO2max quotidien permanent. [Adaptations] Adapter le nombre de séances du bloc au niveau. Allonger la phase d''assimilation si la fatigue persiste.',
 TRUE),
('Time-Crunched (Carmichael)','Haute intensité maximisée sur faible volume hebdomadaire.',
 ARRAY['Volume faible, intensité élevée','2-3 séances intensives par semaine','Sweet spot et VO2max prioritaires','Pour cyclistes très contraints en temps'],
 ARRAY['cyclisme'],'methodologie',
 '[Philosophie] Quand le temps manque, l''intensité compense partiellement le manque de volume. On maximise le stimulus par séance. [Règles] 6-8h par semaine, 2-3 séances intensives (sweet spot, seuil, VO2max). Peu d''endurance pure faute de temps. Récupération entre séances dures. Programme court et dense. [Exclusions] Pas de gros volume aérobie (impossible). Pas adapté aux épreuves très longues. Pas d''enchaînement d''intensité sans récupération. [Adaptations] Si plus de temps ponctuellement, ajouter une sortie longue. À éviter sur le long terme à cause du risque de plateau et de fatigue.',
 TRUE),
('4DP / Sufferfest','Profil 4 dimensions (NM, AC, MAP, FTP) pour cibler les faiblesses.',
 ARRAY['Profil en 4 dimensions de puissance','Entraînement ciblé sur le point faible','Séances structurées par type de rider','Test 4DP de référence'],
 ARRAY['cyclisme'],'methodologie',
 '[Philosophie] Chaque cycliste a un profil unique (Neuromuscular, Anaerobic Capacity, MAP, FTP). On entraîne en priorité la dimension limitante pour le type d''effort visé. [Règles] Établir le profil via le test 4DP. Identifier le rider type et la faiblesse. Prescrire des séances ciblant la dimension faible tout en maintenant les autres. Re-tester régulièrement. [Exclusions] Pas de plan générique ignorant le profil. Pas de focus unique FTP si la faiblesse est ailleurs. [Adaptations] Réorienter le focus selon l''objectif (sprint, contre-la-montre, montagne). Re-tester après chaque bloc majeur.',
 TRUE);

-- ===== HYROX (4) =====
INSERT INTO competences (nom, description_courte, bullets, sports, categorie, prompt_base, is_predefined) VALUES
('Running-engine first','Le moteur course comme priorité absolue de la performance Hyrox.',
 ARRAY['Course = la moitié du chrono, donc priorité','Gros volume de course aérobie','Stations entraînées mais secondaires','Seuil et VO2max course développés'],
 ARRAY['hyrox'],'methodologie',
 '[Philosophie] En Hyrox, 8 km de course représentent la moitié du temps total. Un moteur aérobie supérieur fait la différence ; les stations se gèrent, la course se gagne. [Règles] Prioriser le volume de course (endurance, seuil, VO2max). Entraîner les 8 stations mais comme second pilier. Travailler la course sous fatigue partielle. Maintenir la force fonctionnelle. [Exclusions] Pas de focus force/hypertrophie au détriment de la course. Pas de négligence du volume aérobie. [Adaptations] Si une station est un point noir majeur (ex. sled), lui accorder un bloc spécifique sans sacrifier la course. Adapter au niveau de course initial.',
 TRUE),
('Concurrent hybride','Développement parallèle endurance et force, gestion de l''interférence.',
 ARRAY['Développement simultané force + endurance','Gestion de l''effet d''interférence','Séances combinées et séparées équilibrées','Programmation pour limiter la fatigue croisée'],
 ARRAY['hyrox'],'methodologie',
 '[Philosophie] Hyrox exige force ET endurance. Le défi est l''effet d''interférence : trop de l''un dégrade l''autre. On programme pour développer les deux en limitant le conflit. [Règles] Séparer les qualités quand c''est possible (force le matin, endurance le soir, ou jours distincts). Prioriser la qualité travaillée en début de séance. Périodiser l''emphase selon la phase. Récupération suffisante entre séances lourdes. [Exclusions] Pas de force lourde juste avant une grosse séance d''endurance. Pas d''accumulation de fatigue croisée non gérée. [Adaptations] En approche compétition, basculer vers le spécifique combiné. Réduire le volume de force pur en pic.',
 TRUE),
('Compromised running','Course sous fatigue, simulation de l''enchaînement station → course.',
 ARRAY['Course entraînée en état de fatigue','Transitions station → course répétées','Simulations de format compétition','Gestion de l''allure dégradée'],
 ARRAY['hyrox'],'methodologie',
 '[Philosophie] En course, on ne court jamais frais : chaque kilomètre suit une station épuisante. Il faut entraîner spécifiquement la course sur jambes lourdes. [Règles] Intégrer des séances enchaînant station puis course (ex. sled puis 1 km, wall balls puis 1 km). Simulations partielles ou complètes du format. Travailler la reprise d''allure après l''effort de force. Gérer la dégradation de foulée. [Exclusions] Pas uniquement de la course fraîche isolée. Pas de stations sans transition vers la course. [Adaptations] Doser la fréquence des simulations complètes (très fatigantes). En base, plus de qualités séparées ; en spécifique, plus de compromised running.',
 TRUE),
('Blocs GPP → Spécifique','Préparation physique générale puis spécialisation progressive Hyrox.',
 ARRAY['Phase GPP : base large force + endurance','Transition vers le spécifique compétition','Volume général décroissant, spécifique croissant','Pic calé sur la date de course'],
 ARRAY['hyrox'],'periodisation',
 '[Philosophie] Construire d''abord une base physique générale large (force, endurance, mobilité), puis spécialiser progressivement vers les exigences exactes de la compétition. [Règles] Phase GPP : développement général de la force et de l''endurance, correction des faiblesses. Phase de transition : introduction des stations spécifiques et du compromised running. Phase spécifique : simulations de format, affûtage. Volume général qui décroît à mesure que le spécifique monte. [Exclusions] Pas de spécifique pur sans base générale. Pas de GPP prolongée jusqu''à la compétition. [Adaptations] Allonger la GPP pour un débutant. Raccourcir pour un athlète déjà complet visant un pic rapproché.',
 TRUE);

-- ===== TRIATHLON (7) =====
INSERT INTO competences (nom, description_courte, bullets, sports, categorie, prompt_base, is_predefined) VALUES
('Périodisation Friel','Périodisation linéaire des 3 disciplines vers le pic.',
 ARRAY['Base → Build → Peak → Race sur 3 sports','Volume d''abord, spécifique ensuite','Cycles 3:1 charge/récupération','Suivi CTL/ATL/TSB multi-sport'],
 ARRAY['triathlon'],'periodisation',
 '[Philosophie] Bâtir la forme triathlon par phases progressives sur les trois disciplines, en gérant la charge combinée natation+vélo+course. [Règles] Phases Base, Build, Peak, Race. Volume et technique d''abord, intensité spécifique ensuite. Cycles 3 semaines de charge + 1 de récupération. Suivi de la charge globale via CTL/ATL/TSB. Équilibrer les trois sports selon les forces/faiblesses. [Exclusions] Pas d''intensité maximale en base. Pas de négligence durable d''une discipline. Pas de saut de phase. [Adaptations] Raccourcir Base pour un objectif rapproché. Pondérer le temps par discipline selon les points faibles et le format (sprint à Ironman).',
 TRUE),
('Périodisation inversée (Trisutto)','Intensité maintenue toute l''année, volume ajouté tard.',
 ARRAY['Intensité présente dès le début de saison','Volume spécifique ajouté tardivement','Natation comme pilier central','Approche pragmatique âge-groupe'],
 ARRAY['triathlon'],'periodisation',
 '[Philosophie] À l''inverse du modèle classique, on conserve l''intensité toute l''année et on ajoute le volume près de la compétition. Adapté aux âge-groupes au temps limité. [Règles] Maintenir des séances de qualité régulières en intersaison. Construire la natation comme socle technique central. Ajouter le volume spécifique (longues sorties vélo/course) dans la phase finale. [Exclusions] Pas de longue phase de base purement aérobie sans intensité. Pas d''abandon de l''intensité en hiver. [Adaptations] Pour un Ironman, prévoir tout de même un bloc de volume conséquent en fin de préparation. Adapter au temps disponible de l''athlète.',
 TRUE),
('Méthode Norvégienne triathlon','Double seuil contrôlé au lactate appliqué au triathlon.',
 ARRAY['Double seuil piloté au lactate','Gros volume sub-seuil sur les 3 sports','Doubles séances seuil régulières','Contrôle lactate par discipline'],
 ARRAY['triathlon'],'methodologie',
 '[Philosophie] Transposer la méthode norvégienne au triathlon : maximiser le volume au seuil en contrôlant le lactate, sur les trois disciplines. [Règles] Séances clés au seuil, souvent en double, avec lactate maintenu entre 2 et 4 mmol/L. Gros volume aérobie sub-seuil. Répartir le travail seuil entre natation, vélo et course. Récupération active entre séances dures. [Exclusions] Pas de VO2max courte explosive. Pas de tempo sans contrôle. Pas d''intensité maximale sans récupération. [Adaptations] Sans lactatemètre, piloter à la FC/puissance sub-seuil. Réduire le double seuil si la charge combinée devient excessive.',
 TRUE),
('Polarisation triathlon','Distribution 80/20 répartie sur les trois disciplines.',
 ARRAY['80% facile / 20% dur sur le combiné','Zone intermédiaire évitée','Intensité concentrée sur peu de séances','Volume facile dominant multi-sport'],
 ARRAY['triathlon'],'methodologie',
 '[Philosophie] Appliquer la polarisation à la charge combinée des trois sports : la majorité facile, l''intensité concentrée et vraiment dure. [Règles] 80% du volume total sous LT1, 20% au-dessus de LT2. Concentrer l''intensité sur quelques séances clés par discipline. Le reste en endurance fondamentale. Mesure par temps en zone sur l''ensemble. [Exclusions] Pas de tempo prolongé. Pas de séances modérées multipliées qui saturent la zone grise. [Adaptations] Avant un format long, intégrer du travail à allure spécifique de course. Ajuster la répartition d''intensité selon la discipline faible.',
 TRUE),
('Pyramidale triathlon','Distribution dégressive endurance → seuil → VO2max sur 3 sports.',
 ARRAY['Base aérobie large multi-sport','Seuil intégré en quantité raisonnable','Sommet VO2max réduit','Transition possible vers le polarisé'],
 ARRAY['triathlon'],'methodologie',
 '[Philosophie] Distribution en pyramide sur les trois disciplines : large base aérobie, du seuil en quantité mesurée, peu de très haute intensité. [Règles] ~75% endurance, ~20% tempo/seuil, ~5% VO2max sur le combiné. Une séance seuil et une séance longue par discipline prioritaire. Progression vers plus d''intensité en fin de cycle. [Exclusions] Pas de polarisation stricte en début de préparation. Pas de surcharge VO2max précoce. [Adaptations] Glisser vers polarisé à l''approche de la compétition. Augmenter la base aérobie en intersaison.',
 TRUE),
('Brick training','Enchaînements vélo→course pour adapter les transitions.',
 ARRAY['Enchaînements vélo → course réguliers','Adaptation neuromusculaire à la transition','Gestion des jambes lourdes en T2','Simulation des allures de course'],
 ARRAY['triathlon'],'adaptation',
 '[Philosophie] La transition vélo-course est une compétence spécifique : les jambes lourdes au début du run se travaillent. Le brick prépare le corps et la tête à cet enchaînement. [Règles] Séances brick régulières (vélo puis course immédiate). Travailler la reprise d''une allure cible malgré la fatigue vélo. Varier la durée des deux segments selon le format visé. Intégrer les transitions techniques (T2). [Exclusions] Pas de brick systématique à chaque séance (fatigue). Pas de négligence des séances isolées par discipline. [Adaptations] Doser la fréquence et l''intensité des bricks. Bricks plus longs et spécifiques à l''approche d''un format long.',
 TRUE),
('Périodisation par blocs triathlon','Blocs concentrés sur une discipline à la fois.',
 ARRAY['Bloc concentré sur une discipline dominante','Maintien minimal des deux autres','Rotation des focus par bloc','Assimilation entre blocs'],
 ARRAY['triathlon'],'periodisation',
 '[Philosophie] Concentrer le stimulus sur une discipline à la fois permet un progrès plus marqué, tout en maintenant les deux autres à un niveau d''entretien. [Règles] Bloc dédié à une discipline (ex. vélo) avec volume/intensité accrus, les deux autres en maintien. Rotation des focus sur les blocs successifs. Phase d''assimilation entre blocs. Suivi de la fraîcheur globale. [Exclusions] Pas d''abandon total d''une discipline pendant un bloc. Pas d''enchaînement de blocs durs sans assimilation. [Adaptations] Cibler en priorité la discipline faible. Raccourcir les blocs pour un athlète peu disponible.',
 TRUE);

-- ===== NATATION (6) =====
INSERT INTO competences (nom, description_courte, bullets, sports, categorie, prompt_base, is_predefined) VALUES
('Haut-volume traditionnel (Counsilman)','Gros kilométrage en bassin, base aérobie massive.',
 ARRAY['Kilométrage hebdomadaire très élevé','Base aérobie massive en bassin','Technique travaillée à haut volume','Multiples séances par semaine'],
 ARRAY['natation'],'methodologie',
 '[Philosophie] Le volume construit la nage : un gros kilométrage développe l''endurance, la technique sous fatigue et la capacité aérobie. [Règles] Kilométrage hebdomadaire élevé réparti sur de nombreuses séances. Majorité de nage aérobie avec travail technique constant. Séries longues, éducatifs, et un peu de qualité. Progression par le volume puis l''intensité. [Exclusions] Pas de volume très faible. Pas de focus exclusif sprint. Pas de négligence de la technique. [Adaptations] Réduire le volume pour les âge-groupes au temps limité. Ajouter de la spécificité d''allure à l''approche des compétitions.',
 TRUE),
('USRPT (Rushall)','Répétitions courtes à allure de course, repos courts, échec contrôlé.',
 ARRAY['Répétitions à allure objectif de course','Repos courts, séries arrêtées à l''échec','Faible volume, haute spécificité','Pas de zones aérobies traditionnelles'],
 ARRAY['natation'],'methodologie',
 '[Philosophie] On nage spécifiquement à l''allure de course visée. La spécificité prime sur le volume : répéter l''allure cible jusqu''à ne plus pouvoir la tenir. [Règles] Séries de répétitions courtes à l''allure objectif, repos courts. Arrêter une série quand l''allure n''est plus tenue (échec contrôlé). Volume global faible mais ultra-spécifique. Cibler l''allure exacte de l''épreuve. [Exclusions] Pas de longues séries aérobies lentes. Pas de gros kilométrage non spécifique. Pas de nage à allure indéterminée. [Adaptations] Combinable avec un minimum d''aérobie pour les épreuves longues. Adapter les distances de répétition au format de course.',
 TRUE),
('Zones aérobie/seuil (Maglischo)','Entraînement par zones physiologiques précises.',
 ARRAY['Cinq zones d''intensité codifiées','Travail aérobie, seuil et VO2max ciblés','Équilibre volume/intensité par zone','Approche scientifique de la nage'],
 ARRAY['natation'],'methodologie',
 '[Philosophie] Chaque zone d''intensité développe une qualité physiologique précise. On dose le temps dans chaque zone selon l''objectif. [Règles] Système de zones (endurance basse, aérobie, seuil, VO2max, sprint). Répartition planifiée du volume par zone selon la phase. Séries adaptées à chaque cible physiologique. Technique intégrée en permanence. [Exclusions] Pas de nage à intensité indéterminée. Pas de tout-volume ni de tout-sprint. [Adaptations] Pondérer les zones selon la distance d''épreuve (sprinteur vs demi-fondeur). Ajuster en phase d''affûtage vers plus de spécifique.',
 TRUE),
('Polarisée natation (CSS + 80/20)','Distribution 80/20 autour de la Critical Swim Speed.',
 ARRAY['Pilotage par la CSS (Critical Swim Speed)','80% facile / 20% dur','Zone intermédiaire réduite','Test CSS de référence régulier'],
 ARRAY['natation'],'methodologie',
 '[Philosophie] Polariser la nage autour de la vitesse critique (CSS) : beaucoup de facile, une minorité de dur, peu d''entre-deux. [Règles] Déterminer la CSS via un test (400m + 200m). 80% du volume en aérobie facile, 20% au-dessus de la CSS. Séries qualité autour et au-dessus de la CSS. Re-tester régulièrement. [Exclusions] Pas de séries prolongées en zone intermédiaire. Pas de nage modérée systématique. [Adaptations] Ajouter du spécifique d''allure avant les compétitions. Pour les épreuves longues, intégrer du travail à allure cible sous la CSS.',
 TRUE),
('Sprint moderne','Vitesse maximale, force et puissance, faible volume.',
 ARRAY['Vitesse et puissance maximales prioritaires','Faible volume, haute qualité','Travail de force et de départs','Récupérations longues entre efforts'],
 ARRAY['natation'],'methodologie',
 '[Philosophie] Le sprint se développe par la vitesse maximale, la puissance et la technique fine, pas par le volume. La fraîcheur est la condition de la vélocité. [Règles] Efforts courts à vitesse maximale, récupérations longues et complètes. Travail de force (sec et bassin), départs et virages. Volume hebdomadaire modéré. Qualité de chaque répétition non négociable. [Exclusions] Pas de gros volume aérobie épuisant. Pas de séries qui dégradent la vitesse maximale. [Adaptations] Conserver un socle aérobie minimal pour la récupération. Adapter la part de force au profil de l''athlète.',
 TRUE),
('Périodisation par distance','Préparation périodisée selon la distance d''épreuve.',
 ARRAY['Structure adaptée à la distance cible','Du général vers le spécifique d''allure','Volume et intensité dosés par phase','Affûtage calé sur la compétition'],
 ARRAY['natation'],'periodisation',
 '[Philosophie] La préparation se structure selon la distance de l''épreuve : un 50m et un 1500m n''exigent pas le même équilibre volume/intensité. [Règles] Phase générale (base aérobie et technique), phase spécifique (allure cible de l''épreuve), affûtage. Pondérer volume et intensité selon la distance visée. Cycles de charge et récupération. [Exclusions] Pas de préparation identique pour toutes les distances. Pas d''affûtage négligé. [Adaptations] Sprinteur : plus de qualité, moins de volume. Demi-fondeur/fondeur : base aérobie plus large. Ajuster l''affûtage à la fraîcheur de l''athlète.',
 TRUE);

-- ===== ROWING (6) =====
INSERT INTO competences (nom, description_courte, bullets, sports, categorie, prompt_base, is_predefined) VALUES
('HVLIT (Haut-volume / basse intensité)','Gros volume à basse intensité, base aérobie aviron.',
 ARRAY['Volume élevé à basse intensité (UT2)','Base aérobie dominante','Faible part d''intensité','Technique soignée à bas régime'],
 ARRAY['rowing'],'methodologie',
 '[Philosophie] L''aviron se construit sur un énorme socle aérobie de basse intensité (UT2). La puissance spécifique vient sur cette base. [Règles] Majorité du volume en endurance basse (UT2), longues séances en bateau et à l''ergo. Petite part d''intensité (seuil, race-pace) en complément. Technique travaillée à bas régime. Progression par le volume. [Exclusions] Pas d''excès d''intensité au détriment du volume aérobie. Pas de race-pace quotidien. [Adaptations] Augmenter la part race-pace à l''approche des compétitions. Adapter le ratio ergo/eau selon la saison.',
 TRUE),
('Pyramidal aviron','Distribution dégressive UT2 → seuil → puissance.',
 ARRAY['Base UT2 large, sommet intense réduit','Seuil intégré en quantité modérée','Transition possible vers le polarisé','Travail multi-zones structuré'],
 ARRAY['rowing'],'methodologie',
 '[Philosophie] Construire en pyramide : large base UT2, du seuil en quantité raisonnable, peu de puissance maximale. La zone intermédiaire a sa valeur. [Règles] ~75% en UT2, ~20% en seuil/UT1, ~5% en puissance/VO2max. Une séance seuil et une longue par semaine. Progression vers plus d''intensité en fin de cycle. [Exclusions] Pas de polarisation stricte en début de préparation. Pas de surcharge de puissance précoce. [Adaptations] Glisser vers polarisé à l''approche des régates. Augmenter la base UT2 en intersaison.',
 TRUE),
('Polarisée aviron','Distribution 80/20 entre UT2 et haute intensité.',
 ARRAY['80% en UT2, 20% au-dessus du seuil','Zone intermédiaire évitée','Intensité concentrée sur peu de séances','Mesure par temps en zone'],
 ARRAY['rowing'],'methodologie',
 '[Philosophie] Séparer nettement le facile (UT2) et le dur : la zone intermédiaire fatigue sans le rendement des extrêmes. [Règles] 80% du volume en UT2, 20% au-dessus du seuil (race-pace, VO2max). Concentrer l''intensité sur quelques séances clés. Le reste en endurance basse. Mesure par temps en zone. [Exclusions] Pas de seuil prolongé continu. Pas de séances modérées multipliées. [Adaptations] Avant une régate, intégrer du race-pace spécifique. Ajuster la part d''intensité selon la distance de course (2000m).',
 TRUE),
('Modèle allemand / GDR (lactate)','Pilotage précis par paliers de lactate, gros volume.',
 ARRAY['Pilotage par paliers de lactate','Gros volume contrôlé physiologiquement','Tests lactate réguliers','Approche systématique héritée du rowing est-allemand'],
 ARRAY['rowing'],'methodologie',
 '[Philosophie] Hérité de l''école est-allemande : contrôler précisément l''intensité par le lactate pour optimiser chaque séance et éviter la dérive. [Règles] Définir les zones par paliers de lactate via tests réguliers. Gros volume aérobie en zones basses contrôlées, travail seuil ciblé. Suivi systématique des marqueurs physiologiques. [Exclusions] Pas d''intensité à l''aveugle. Pas de séances dont la zone n''est pas contrôlée. [Adaptations] Sans accès au lactate, approximer par puissance/FC sur ergo calibré. Augmenter le race-pace en phase de compétition.',
 TRUE),
('Race-pace specific','Travail spécifique à l''allure de course 2000m.',
 ARRAY['Répétitions à l''allure 2000m','Spécificité de la cadence de course','Tolérance lactique race-pace','Volume aérobie en soutien'],
 ARRAY['rowing'],'methodologie',
 '[Philosophie] La performance sur 2000m se prépare en nageant souvent l''allure et la cadence exactes de la course. La spécificité prime à l''approche de l''objectif. [Règles] Répétitions à l''allure/puissance 2000m avec cadence de course. Travail de tolérance lactique. Volume aérobie maintenu en soutien. Simulations partielles de course. [Exclusions] Pas uniquement de l''aérobie lente loin de l''objectif. Pas de cadence non spécifique sur les séries clés. [Adaptations] Doser le race-pace (très exigeant). En base, privilégier l''aérobie ; en spécifique, augmenter le race-pace.',
 TRUE),
('Périodisation traditionnelle + ratio ergo/eau','Périodisation classique avec dosage ergomètre/bateau.',
 ARRAY['Base → spécifique → affûtage','Ratio ergo/eau ajusté par saison','Volume hivernal sur ergo, spécifique sur l''eau','Progression linéaire vers les régates'],
 ARRAY['rowing'],'periodisation',
 '[Philosophie] Périodiser classiquement (base, spécifique, affûtage) en ajustant le ratio ergomètre/bateau selon la saison et la météo. [Règles] Hiver : gros volume sur ergo, base aérobie et force. Printemps/été : transfert sur l''eau, travail spécifique et technique de bateau. Affûtage avant les régates. Cycles de charge/récupération. [Exclusions] Pas de tout-ergo toute l''année. Pas de spécifique sans base hivernale. [Adaptations] Ajuster le ratio selon l''accès au plan d''eau. Allonger la base pour un rameur en construction.',
 TRUE);

-- ===== MUSCULATION - FORCE (7) =====
INSERT INTO competences (nom, description_courte, bullets, sports, categorie, prompt_base, is_predefined) VALUES
('Westside Conjugate','Méthode conjuguée : effort maximal, dynamique et répété.',
 ARRAY['Max Effort + Dynamic Effort + Repeated Effort','Rotation des exercices max effort','Bandes et chaînes (accommodating resistance)','Travail des points faibles ciblé'],
 ARRAY['muscu'],'force',
 '[Philosophie] Développer simultanément la force maximale, la vitesse-force et l''hypertrophie via la méthode conjuguée. La variété des exercices évite la stagnation. [Règles] Jours Max Effort (charges maximales sur variations tournantes), jours Dynamic Effort (vitesse, bandes/chaînes), travail Repeated Effort pour les accessoires et points faibles. Rotation fréquente des exercices principaux. [Exclusions] Pas de répétition figée du même max effort chaque semaine. Pas d''absence de travail vitesse. Pas de négligence des points faibles. [Adaptations] Pour un débutant, simplifier (la méthode est avancée). Adapter le volume d''accessoires selon la récupération.',
 TRUE),
('Sheiko','Haut volume d''intensité modérée-élevée, fréquence élevée.',
 ARRAY['Volume élevé sur les mouvements de force','Fréquence élevée squat/bench/deadlift','Technique perfectionnée par la répétition','Programmation détaillée et planifiée'],
 ARRAY['muscu'],'force',
 '[Philosophie] La maîtrise technique et la force se construisent par un volume important d''intensité modérée-élevée, répété fréquemment sur les trois mouvements. [Règles] Programmes détaillés avec fréquence élevée de squat, bench et deadlift. Volume élevé à intensité modérée-haute (pas de max permanent). Technique travaillée à chaque série. Progression planifiée par cycles. [Exclusions] Pas de travail à l''échec systématique. Pas de maxs répétés chaque séance. Pas d''improvisation hors programme. [Adaptations] Volume à adapter au niveau (les versions élite sont très denses). Réduire la fréquence si la récupération est insuffisante.',
 TRUE),
('5/3/1 (Wendler)','Progression lente basée sur des pourcentages du max.',
 ARRAY['Cycles mensuels 5/3/1 sur le max','Progression incrémentale lente','Travail principal + assistance','Simplicité et durabilité long terme'],
 ARRAY['muscu'],'force',
 '[Philosophie] La progression durable bat les gains rapides. On avance lentement mais sûrement par petits incréments sur un Training Max conservateur. [Règles] Cycles de 4 semaines (5/3/1/deload) basés sur un Training Max (~90% du max réel). Un mouvement principal par séance + assistance. Incrémenter le TM chaque cycle. Patience et constance. [Exclusions] Pas de max permanent. Pas d''ajout d''intensité hors protocole. Pas d''impatience sur les incréments. [Adaptations] Nombreux templates (BBB, FSL) selon l''objectif (force ou volume). Adapter l''assistance aux faiblesses et au sport pratiqué.',
 TRUE),
('Texas Method','Volume, récupération, intensité sur la semaine.',
 ARRAY['Lundi volume, mercredi léger, vendredi intensité','Progression hebdomadaire (pas par séance)','Pour intermédiaires sortis du linéaire','Trois mouvements principaux'],
 ARRAY['muscu'],'force',
 '[Philosophie] Pour l''intermédiaire qui ne progresse plus séance par séance : on organise la surcharge sur la semaine entière. [Règles] Jour volume (lundi, séries lourdes multiples), jour récupération (mercredi, léger), jour intensité (vendredi, record de répétitions ou nouveau max). Progression hebdomadaire. Trois mouvements principaux. [Exclusions] Pas de progression linéaire séance par séance (dépassée). Pas de jour léger transformé en jour dur. [Adaptations] Ajuster le volume du lundi selon la récupération. Décliner sur d''autres mouvements selon les besoins.',
 TRUE),
('Smolov','Cycle de squat très intense et très exigeant.',
 ARRAY['Spécialisation squat extrême','Fréquence et volume très élevés','Gains de force rapides mais coûteux','Récupération maximale exigée'],
 ARRAY['muscu'],'force',
 '[Philosophie] Un cycle de spécialisation brutal pour faire exploser le squat sur quelques semaines, au prix d''une fatigue considérable. [Règles] Fréquence et volume de squat très élevés sur le cycle (base mesocycle puis intense). Progression agressive des charges. Récupération, sommeil et nutrition maximisés. Réservé aux pratiquants confirmés. [Exclusions] Pas pour un débutant. Pas de concurrence avec d''autres entraînements lourds (course, autre cycle force). Pas de saut de séances. [Adaptations] Versions allégées (Smolov Jr) pour bench ou athlètes moins avancés. À placer en intersaison, jamais en pleine charge d''un autre sport.',
 TRUE),
('RTS (Reactive Training Systems)','Autorégulation par RPE et fatigue percues.',
 ARRAY['Charges pilotées par le RPE','Autorégulation jour par jour','Gestion de la fatigue individualisée','Approche basée sur les données'],
 ARRAY['muscu'],'force',
 '[Philosophie] La charge optimale varie chaque jour selon la forme. On autorégule via le RPE et les indicateurs de fatigue plutôt que par des pourcentages fixes. [Règles] Sélection des charges par RPE cible (ex. RPE 8 = 2 reps en réserve). Ajuster le volume selon la fatigue du jour. Suivre les données pour individualiser. Progression guidée par la réponse réelle. [Exclusions] Pas de pourcentages rigides ignorant la forme du jour. Pas de travail systématique à l''échec. [Adaptations] Pour un débutant, apprendre d''abord à estimer le RPE. Combiner avec des cibles de volume pour structurer.',
 TRUE),
('Méthode bulgare','Maxs quasi quotidiens sur peu de mouvements.',
 ARRAY['Travail au max quasi quotidien','Très peu de mouvements','Spécificité extrême','Réservé aux athlètes très avancés'],
 ARRAY['muscu'],'force',
 '[Philosophie] La spécificité poussée à l''extrême : monter au maximum du jour, presque chaque jour, sur très peu d''exercices. Le corps s''adapte à être toujours proche du max. [Règles] Trouver un max quotidien (daily max) sur un ou deux mouvements. Très haute fréquence, faible variété. Peu de volume au-delà du max. Réservé aux athlètes très avancés et résilients. [Exclusions] Pas pour un débutant ou intermédiaire. Pas de gros volume accessoire. Pas de concurrence avec un autre sport exigeant. [Adaptations] Introduire des fourchettes (top single + back-off) pour gérer la fatigue. À éviter totalement en charge d''un sport d''endurance.',
 TRUE);

-- ===== MUSCULATION - HYPERTROPHIE (5) =====
INSERT INTO competences (nom, description_courte, bullets, sports, categorie, prompt_base, is_predefined) VALUES
('DUP (Daily Undulating Periodization)','Variation quotidienne des intensités et volumes.',
 ARRAY['Intensité/volume variés à chaque séance','Stimulus varié force + hypertrophie','Fréquence élevée par groupe','Flexibilité de programmation'],
 ARRAY['muscu'],'hypertrophie',
 '[Philosophie] Varier l''intensité et le volume au jour le jour stimule plusieurs qualités et limite l''accoutumance, favorisant l''hypertrophie et la force. [Règles] Alterner les séances (ex. lourd/peu de reps, modéré, léger/beaucoup de reps) sur la semaine. Fréquence élevée par groupe musculaire. Volume hebdomadaire suffisant pour l''hypertrophie. Progression sur chaque type de séance. [Exclusions] Pas de schéma figé identique chaque séance. Pas de négligence du volume total. [Adaptations] Simplifier pour un débutant (linéaire d''abord). Ajuster la répartition force/hypertrophie selon l''objectif.',
 TRUE),
('Push/Pull/Legs (haute fréquence)','Répartition poussée/tirage/jambes à fréquence élevée.',
 ARRAY['Split Push / Pull / Legs','Fréquence 2x par groupe et plus','Volume réparti et récupération optimisée','Structure populaire et efficace'],
 ARRAY['muscu'],'hypertrophie',
 '[Philosophie] Organiser l''entraînement par patterns (pousser, tirer, jambes) permet une fréquence élevée par groupe musculaire avec une bonne récupération locale. [Règles] Rotation Push / Pull / Legs, souvent 6 jours pour 2x par groupe. Volume hebdomadaire élevé réparti sur les séances. Progression en charge et en reps. Récupération entre sollicitations du même groupe. [Exclusions] Pas de chevauchement mal géré (épaules surchargées). Pas de volume insuffisant par groupe. [Adaptations] Version 3 jours (1x par groupe) pour les emplois du temps serrés. Ajuster le volume au niveau et à la récupération.',
 TRUE),
('Bro split','Un groupe musculaire par jour, gros volume local.',
 ARRAY['Un groupe musculaire par séance','Volume local très élevé','Fréquence faible (1x par groupe)','Focus congestion et isolation'],
 ARRAY['muscu'],'hypertrophie',
 '[Philosophie] Marteler un groupe musculaire par séance avec un gros volume local maximise la congestion et la sollicitation, avec une semaine complète de récupération par groupe. [Règles] Un groupe par jour (ex. pecs, dos, jambes, épaules, bras). Volume local élevé, exercices variés, isolation marquée. Fréquence d''une fois par groupe et par semaine. [Exclusions] Pas de fréquence élevée par groupe (ce n''est pas le but). Pas de volume insuffisant le jour dédié. [Adaptations] Mieux adapté aux pratiquants avancés disposant de temps. Pour optimiser, surveiller que le volume hebdomadaire par groupe reste suffisant.',
 TRUE),
('HST (Hypertrophy Specific Training)','Fréquence élevée, charges progressives, déconditionnement stratégique.',
 ARRAY['Fréquence élevée par muscle','Progression de charge sur 2 semaines','Strategic deconditioning périodique','Reps dégressives (15→10→5)'],
 ARRAY['muscu'],'hypertrophie',
 '[Philosophie] L''hypertrophie répond à une charge mécanique progressive et fréquente. On resensibilise périodiquement le muscle par un déconditionnement stratégique. [Règles] Fréquence élevée (corps entier 3x/semaine). Blocs de répétitions dégressifs (15, puis 10, puis 5) avec charges croissantes sur deux semaines par palier. Strategic deconditioning (repos/léger) avant de recommencer un cycle plus lourd. [Exclusions] Pas de travail à l''échec permanent. Pas de fréquence faible. [Adaptations] Ajuster le nombre d''exercices au temps disponible. Allonger le déconditionnement si la fatigue s''accumule.',
 TRUE),
('GVT (German Volume Training)','Dix séries de dix répétitions sur un mouvement clé.',
 ARRAY['10 séries de 10 répétitions','Volume local très élevé','Charge modérée (~60% du max)','Phase d''hypertrophie courte et intense'],
 ARRAY['muscu'],'hypertrophie',
 '[Philosophie] Un volume massif (10x10) sur un mouvement composé soumet le muscle à un stress métabolique et mécanique élevé, déclenchant une forte hypertrophie. [Règles] 10 séries de 10 répétitions sur un mouvement principal par groupe, charge modérée (~60% du max), repos courts contrôlés. Peu d''accessoires en plus. Cycle court (4-6 semaines) car très exigeant. [Exclusions] Pas de charges lourdes (impossible à 10x10). Pas de prolongation excessive du cycle. Pas pour un débutant non préparé. [Adaptations] Réduire à 10x8 pour débuter. Placer en bloc dédié, hors période de charge d''un sport d''endurance.',
 TRUE);

-- ===== MUSCULATION - PERFORMANCE (4) =====
INSERT INTO competences (nom, description_courte, bullets, sports, categorie, prompt_base, is_predefined) VALUES
('Périodisation par blocs (Verkhoshansky)','Blocs concentrés d''accumulation, transformation, réalisation.',
 ARRAY['Blocs Accumulation → Transformation → Réalisation','Charges concentrées par qualité','Effet retardé de la charge (long-term delayed)','Pour athlètes de force-vitesse'],
 ARRAY['muscu'],'performance',
 '[Philosophie] Concentrer un fort volume d''une qualité sur un bloc produit un effet d''entraînement retardé exploité au bloc suivant. La séquence accumulation→transformation→réalisation amène le pic. [Règles] Bloc d''accumulation (volume, force générale), bloc de transformation (intensité, force-vitesse), bloc de réalisation (puissance/spécifique, affûtage). Concentration des charges. Suivi de la fatigue et de la supercompensation. [Exclusions] Pas de mélange uniforme de toutes les qualités. Pas d''enchaînement sans phase de réalisation. [Adaptations] Adapter la durée des blocs au niveau et au calendrier. Caler la réalisation sur la date de compétition.',
 TRUE),
('Méthode triphasique (Dietz)','Travail excentrique, isométrique puis concentrique.',
 ARRAY['Trois phases : excentrique, isométrique, concentrique','Décomposition du mouvement sportif','Transfert vers la puissance explosive','Pré-compétition spécifique'],
 ARRAY['muscu'],'performance',
 '[Philosophie] Tout mouvement explosif comporte trois phases (excentrique, isométrique, concentrique). Les entraîner séparément puis les réintégrer améliore la puissance et le transfert sportif. [Règles] Bloc excentrique (tempo lent contrôlé), bloc isométrique (pauses sous tension), bloc concentrique/explosif (vitesse maximale). Progression vers le mouvement complet explosif. Placé en pré-compétition. [Exclusions] Pas de phases mélangées sans structure. Pas pour un débutant sans base de force. [Adaptations] Doser le volume excentrique (très traumatisant). Raccourcir les blocs pour un calendrier serré.',
 TRUE),
('French Contrast','Combinaison lourd + explosif + pliométrie + survitesse.',
 ARRAY['Complexe : lourd, balistique, plyo, assisté','Potentiation post-activation','Développement de la puissance maximale','Réservé aux athlètes avancés'],
 ARRAY['muscu'],'performance',
 '[Philosophie] Combiner dans un même complexe un exercice lourd, un balistique, un pliométrique et un survitesse exploite la potentiation post-activation pour maximiser la puissance. [Règles] Enchaîner 4 exercices : lourd (force), balistique (ex. saut chargé), pliométrique (saut), assisté/survitesse, avec récupérations adaptées. Faible volume, qualité maximale. Réservé aux athlètes avancés bien préparés. [Exclusions] Pas pour un débutant. Pas de fatigue accumulée qui ruine l''explosivité. Pas de volume excessif. [Adaptations] Simplifier en contraste à 2 exercices pour débuter. Placer loin des grosses séances d''endurance.',
 TRUE),
('Linéaire vs Ondulée','Comparaison/choix entre progression linéaire et ondulée.',
 ARRAY['Linéaire : progression régulière par phases','Ondulée : variation fréquente des paramètres','Choix selon niveau et objectif','Cadre de décision méthodologique'],
 ARRAY['muscu'],'performance',
 '[Philosophie] Deux logiques de progression coexistent : linéaire (montée régulière de l''intensité par phases) et ondulée (variation fréquente du volume/intensité). Le choix dépend du profil et de l''objectif. [Règles] Linéaire : idéale pour les débutants et la construction de base, phases successives claires. Ondulée : adaptée aux intermédiaires/avancés, varie les stimuli pour éviter la stagnation. Choisir et appliquer un cadre cohérent. [Exclusions] Pas de mélange incohérent des deux sans logique. Pas d''ondulée chaotique sans cible. [Adaptations] Débuter en linéaire puis basculer en ondulé avec l''expérience. Adapter au calendrier de compétition.',
 TRUE);

-- ===== NUTRITION TRANSVERSALE (5) =====
INSERT INTO competences (nom, description_courte, bullets, sports, categorie, prompt_base, is_predefined) VALUES
('Low-Carb / High-Fat','Alimentation pauvre en glucides, riche en lipides.',
 ARRAY['Glucides réduits, lipides élevés','Adaptation à l''oxydation des graisses','Adapté à l''endurance de basse intensité','Stabilité glycémique recherchée'],
 ARRAY['transversale'],'nutrition',
 '[Philosophie] Habituer le corps à utiliser les lipides comme carburant principal améliore l''autonomie en endurance et stabilise la glycémie. [Règles] Apport glucidique faible, lipides élevés, protéines adéquates. Favoriser les aliments bruts et les bonnes graisses. Adapté aux efforts longs de basse intensité. Phase d''adaptation de plusieurs semaines. [Exclusions] Ne pas imposer en pleine préparation d''efforts très intenses dépendants du glycogène. Pas de carence (fibres, micronutriments). [Adaptations] Réintroduire des glucides ciblés autour des séances de haute intensité ou des compétitions (approche plus nuancée). Suivre la tolérance individuelle.',
 TRUE),
('High-Carb Performance','Apport glucidique élevé pour soutenir l''intensité.',
 ARRAY['Glucides élevés autour de l''effort','Glycogène musculaire maximisé','Soutien des séances intenses et longues','Ravitaillement pendant l''effort'],
 ARRAY['transversale'],'nutrition',
 '[Philosophie] Le glycogène est le carburant clé de l''intensité. Un apport glucidique élevé soutient les séances dures, accélère la récupération et la performance. [Règles] Apport glucidique élevé, modulé autour des séances (avant, pendant, après). Ravitaillement glucidique pendant les efforts longs/intenses. Recharge post-effort prioritaire. Adapter la quantité au volume d''entraînement. [Exclusions] Pas de restriction glucidique avant les grosses séances ou compétitions. Pas de sous-alimentation chronique (RED-S). [Adaptations] Moduler à la baisse les jours de repos ou de faible volume (nutrition périodisée). Choisir des sources adaptées à la tolérance digestive.',
 TRUE),
('Train Low, Compete High','S''entraîner parfois à faible disponibilité glucidique, concourir avec réserves pleines.',
 ARRAY['Certaines séances en faible disponibilité glucidique','Compétitions avec réserves pleines','Adaptations mitochondriales recherchées','Périodisation fine des glucides'],
 ARRAY['transversale'],'nutrition',
 '[Philosophie] Réaliser certaines séances à faible disponibilité en glycogène amplifie les adaptations aérobies, tout en concourant avec des réserves pleines pour la performance. [Règles] Cibler quelques séances spécifiques (souvent basse intensité, à jeun ou après déplétion) en train low. Reconstituer le glycogène pour les séances clés et les compétitions. Maintenir un apport protéique suffisant. [Exclusions] Pas de train low sur les séances de haute intensité (qualité dégradée). Pas de déficit chronique. Pas pour un athlète fragile ou en croissance. [Adaptations] Fréquence limitée et encadrée. Combiner avec une recharge stricte avant les objectifs.',
 TRUE),
('Jeûne intermittent 16/8','Fenêtre alimentaire restreinte à 8 heures.',
 ARRAY['Fenêtre alimentaire de 8h, jeûne de 16h','Gestion du poids et de la sensibilité insulinique','Timing des repas autour de l''entraînement','Confort digestif pour certains'],
 ARRAY['transversale'],'nutrition',
 '[Philosophie] Concentrer les apports sur une fenêtre de 8h peut aider la gestion du poids, la sensibilité à l''insuline et le confort digestif, sans réduire nécessairement la qualité d''entraînement. [Règles] Fenêtre alimentaire de 8h, jeûne de 16h. Caler les séances clés et les repas principaux dans la fenêtre. Assurer l''apport calorique et protéique total nécessaire. Hydratation pendant le jeûne. [Exclusions] Pas de séances intenses prolongées juste avant la rupture du jeûne sans ravitaillement. Pas de déficit énergétique non maîtrisé. [Adaptations] Déplacer la fenêtre selon l''horaire d''entraînement. À éviter en grosse charge si la couverture des besoins devient difficile.',
 TRUE),
('Nutrition périodisée','Apports adaptés au type et à la charge de chaque séance.',
 ARRAY['Glucides modulés selon la séance','Plus de glucides les jours durs, moins les jours faciles','Protéines réparties sur la journée','Synchronisation nutrition/entraînement'],
 ARRAY['transversale'],'nutrition',
 '[Philosophie] L''alimentation doit suivre l''entraînement : plus de glucides les jours durs, moins les jours faciles. On synchronise les apports avec les besoins réels de chaque séance. [Règles] Moduler les glucides selon l''intensité/volume du jour. Maintenir un apport protéique régulier réparti. Ravitailler autour des séances clés et recharger après. Ajuster les calories à la charge globale. [Exclusions] Pas d''apport fixe identique tous les jours. Pas de sous-alimentation les jours durs. [Adaptations] Affiner selon les objectifs (perte de masse, performance). Surveiller l''énergie disponible pour éviter le RED-S.',
 TRUE);

-- ===== RÉCUPÉRATION TRANSVERSALE (3) =====
INSERT INTO competences (nom, description_courte, bullets, sports, categorie, prompt_base, is_predefined) VALUES
('Récupération active prioritaire','Récupération par le mouvement léger plutôt que le repos total.',
 ARRAY['Mouvement léger entre séances dures','Circulation et élimination favorisées','Jours off remplacés par de l''actif doux','Mobilité et technique à bas régime'],
 ARRAY['transversale'],'recuperation',
 '[Philosophie] Le mouvement léger accélère la récupération en favorisant la circulation et l''élimination des déchets, mieux que le repos complet dans bien des cas. [Règles] Intercaler des séances de récupération active (footing très lent, vélo facile, natation souple, mobilité) entre les séances dures. Garder l''intensité vraiment basse. Travailler la technique et la mobilité à bas régime. [Exclusions] Pas de récupération active qui devient une vraie séance. Pas de suppression du repos complet quand la fatigue est profonde. [Adaptations] Conserver de vrais jours off en cas de fatigue marquée ou de maladie. Doser selon le ressenti et les marqueurs (HRV, sommeil).',
 TRUE),
('Sommeil optimisé (9h+)','Le sommeil comme premier levier de récupération.',
 ARRAY['Cible de 9h+ de sommeil pour les athlètes','Régularité des horaires de coucher','Hygiène de sommeil stricte','Sieste stratégique possible'],
 ARRAY['transversale'],'recuperation',
 '[Philosophie] Le sommeil est le levier de récupération le plus puissant et le plus sous-estimé. La performance se construit autant la nuit qu''à l''entraînement. [Règles] Viser 9h+ de sommeil pour les athlètes en charge. Régularité des horaires de coucher/lever. Hygiène stricte : obscurité, fraîcheur, écrans coupés, caféine gérée. Sieste stratégique courte si besoin. Prioriser le sommeil avant les grosses séances. [Exclusions] Pas de sacrifice du sommeil pour ajouter du volume. Pas de séances tardives intenses qui dégradent l''endormissement. [Adaptations] Ajuster la cible au besoin individuel. Renforcer le sommeil en période de surcharge ou de compétition.',
 TRUE),
('Cryothérapie systématique','Usage du froid pour accélérer la récupération.',
 ARRAY['Froid (bains glacés, cryo) après l''effort','Réduction de l''inflammation et des courbatures','Récupération entre compétitions rapprochées','Timing à éloigner des séances d''adaptation'],
 ARRAY['transversale'],'recuperation',
 '[Philosophie] Le froid réduit l''inflammation et les sensations de courbatures, utile pour récupérer vite entre efforts rapprochés. À utiliser avec discernement car il peut atténuer certaines adaptations. [Règles] Bains froids ou cryothérapie après les efforts quand une récupération rapide prime (tournois, compétitions rapprochées). Protocoles courts et contrôlés. Hydratation et réchauffement après. [Exclusions] Pas de froid juste après une séance de force/hypertrophie visant l''adaptation (peut limiter les gains). Pas d''usage systématique en phase de construction. [Adaptations] Réserver le froid aux périodes de compétition ou de récupération prioritaire. Éloigner des séances clés d''adaptation.',
 TRUE);
