import type { PageOnboardingConfig } from '../system/types'

export const RECOVERY_ONBOARDING: PageOnboardingConfig = {
  pageId: 'recovery',
  version: 2,
  slides: [
    {
      id: 'recovery_status',
      badge: 'État du jour',
      badgeKey: 'onbcfg.recoveryStatusBadge',
      title: 'Ton état de forme en temps réel',
      titleKey: 'onbcfg.recoveryStatusTitle',
      description: "La page Récupération analyse ta charge d'entraînement des derniers jours pour estimer si ton corps est prêt pour un effort intense, modéré ou s'il a besoin de repos.",
      descriptionKey: 'onbcfg.recoveryStatusDesc',
      keyPoints: [
        'Score de forme basé sur CTL, ATL et TSB',
        'Recommandation du jour : Intensif / Modéré / Repos',
        'Tendance sur 7 jours',
      ],
      keyPointsKeys: [
        'onbcfg.recoveryStatusKp1',
        'onbcfg.recoveryStatusKp2',
        'onbcfg.recoveryStatusKp3',
      ],
      visual: 'stats',
      visualConfig: {
        stats: [
          { label: 'Forme (CTL)', labelKey: 'onbcfg.statFormeCtl', value: 71, suffix: '', color: '#10B981' },
          { label: 'Fatigue (ATL)', labelKey: 'onbcfg.statFatigueAtl', value: 88, suffix: '', color: '#EF4444' },
          { label: 'Fraîcheur', labelKey: 'onbcfg.statFraicheur', value: -17, suffix: '', color: '#F59E0B' },
        ],
      },
      features: ['recovery_status', 'ctl_atl_tsb', 'daily_recommendation'],
    },
    {
      id: 'recovery_wellness',
      badge: 'Bien-être',
      badgeKey: 'onbcfg.recoveryWellnessBadge',
      title: 'Saisis tes données de bien-être',
      titleKey: 'onbcfg.recoveryWellnessTitle',
      description: "Chaque matin, note ton sommeil, ton HRV, ta fatigue musculaire et ton humeur. Ces données enrichissent l'analyse et personnalisent les recommandations.",
      descriptionKey: 'onbcfg.recoveryWellnessDesc',
      keyPoints: [
        'Durée et qualité de sommeil',
        'HRV (variabilité cardiaque)',
        'Fatigue musculaire de 1 à 10',
        'Humeur et motivation',
      ],
      keyPointsKeys: [
        'onbcfg.recoveryWellnessKp1',
        'onbcfg.recoveryWellnessKp2',
        'onbcfg.recoveryWellnessKp3',
        'onbcfg.recoveryWellnessKp4',
      ],
      visual: 'icon_grid',
      visualConfig: {
        icons: [
          { label: 'Sommeil', labelKey: 'onbcfg.iconSommeil', color: '#8B5CF6' },
          { label: 'HRV', color: '#EF4444' },
          { label: 'Muscles', color: '#F59E0B' },
          { label: 'Humeur', labelKey: 'onbcfg.iconHumeur', color: '#10B981' },
        ],
      },
      features: ['sleep_tracking', 'hrv_input', 'muscle_fatigue', 'mood'],
    },
    {
      id: 'recovery_trends',
      badge: 'Tendances',
      badgeKey: 'onbcfg.recoveryTrendsBadge',
      title: 'Évolution sur 4 semaines',
      titleKey: 'onbcfg.recoveryTrendsTitle',
      description: "Le graphique CTL/ATL/TSB te montre comment évolue ta forme, ta fatigue et ta fraîcheur sur le long terme. Identifie les pics de fatigue et anticipe les phases de super-compensation.",
      descriptionKey: 'onbcfg.recoveryTrendsDesc',
      keyPoints: [
        'CTL (Forme) : charge chronique, évolue lentement',
        'ATL (Fatigue) : charge aiguë, réagit vite',
        'TSB (Fraîcheur) : différence CTL - ATL',
        'Optimal pour compétition : TSB positif',
      ],
      keyPointsKeys: [
        'onbcfg.recoveryTrendsKp1',
        'onbcfg.recoveryTrendsKp2',
        'onbcfg.recoveryTrendsKp3',
        'onbcfg.recoveryTrendsKp4',
      ],
      visual: 'chart',
      visualConfig: {
        type: 'triple_line',
        data1: [55, 58, 62, 60, 65, 68, 66, 70, 68, 72, 71, 74, 73, 76],
        data2: [50, 65, 72, 58, 70, 80, 65, 78, 72, 82, 75, 70, 65, 60],
        data3: [5, -7, -10, 2, -5, -12, 1, -8, -4, -10, -4, 4, 8, 16],
        color1: '#10B981',
        color2: '#EF4444',
        color3: '#06B6D4',
        label1: 'CTL',
        label2: 'ATL',
        label3: 'TSB',
      },
      features: ['ctl_chart', 'atl_chart', 'tsb_chart'],
    },
    {
      id: 'recovery_protocol',
      badge: 'Protocoles',
      badgeKey: 'onbcfg.recoveryProtocolBadge',
      title: 'Protocoles de récupération',
      titleKey: 'onbcfg.recoveryProtocolTitle',
      description: "Accède à des protocoles guidés : étirements post-séance, bains froids, massages, nutrition de récupération. Chaque protocole est adapté au sport pratiqué.",
      descriptionKey: 'onbcfg.recoveryProtocolDesc',
      keyPoints: [
        'Étirements guidés par groupe musculaire',
        'Nutrition post-effort recommandée',
        "Durée de récupération estimée selon l'effort",
      ],
      keyPointsKeys: [
        'onbcfg.recoveryProtocolKp1',
        'onbcfg.recoveryProtocolKp2',
        'onbcfg.recoveryProtocolKp3',
      ],
      visual: 'icon_grid',
      visualConfig: {
        icons: [
          { label: 'Étirements', labelKey: 'onbcfg.iconEtirements', color: '#06B6D4' },
          { label: 'Nutrition', color: '#10B981' },
          { label: 'Bain froid', labelKey: 'onbcfg.iconBainFroid', color: '#3B82F6' },
          { label: 'Sommeil', labelKey: 'onbcfg.iconSommeil', color: '#8B5CF6' },
        ],
      },
      features: ['recovery_protocols', 'stretching_guide', 'nutrition_recovery'],
    },
  ],
}
