import type { PageOnboardingConfig } from '../system/types'

export const SESSION_ONBOARDING: PageOnboardingConfig = {
  pageId: 'session',
  version: 2,
  slides: [
    {
      id: 'session_library',
      badge: 'Bibliothèque',
      badgeKey: 'onbcfg.sessionLibraryBadge',
      title: 'Tes séances, toujours disponibles',
      titleKey: 'onbcfg.sessionLibraryTitle',
      description: "La bibliothèque centralise toutes tes séances créées, classées par sport. Retrouve-les en quelques secondes pour les réutiliser dans le planning ou les lancer directement.",
      descriptionKey: 'onbcfg.sessionLibraryDesc',
      keyPoints: [
        "Filtrage par sport, durée ou type d'effort",
        'Recherche par nom ou exercice',
        'Séances de la semaine en cours mises en avant',
      ],
      keyPointsKeys: [
        'onbcfg.sessionLibraryKp1',
        'onbcfg.sessionLibraryKp2',
        'onbcfg.sessionLibraryKp3',
      ],
      visual: 'mockup',
      visualConfig: { type: 'session_library_list' },
      features: ['session_library', 'search', 'filters'],
    },
    {
      id: 'session_circuit_types',
      badge: 'Types de circuits',
      badgeKey: 'onbcfg.sessionCircuitBadge',
      title: '5 types de circuits disponibles',
      titleKey: 'onbcfg.sessionCircuitTitle',
      description: "Chaque type de circuit correspond à une logique d'entraînement différente. De la série classique au Tabata, chaque format est géré différemment en temps réel.",
      descriptionKey: 'onbcfg.sessionCircuitDesc',
      keyPoints: [
        'Séries : même exercice répété X fois avec repos',
        'Lap : plusieurs exos enchaînés, répétés en circuit',
        'Superset : 2-3 exos consécutifs sans repos entre eux',
        'EMOM : un exercice par minute, le reste est du repos',
        'Tabata : 20s effort / 10s repos × 8 rounds',
      ],
      keyPointsKeys: [
        'onbcfg.sessionCircuitKp1',
        'onbcfg.sessionCircuitKp2',
        'onbcfg.sessionCircuitKp3',
        'onbcfg.sessionCircuitKp4',
        'onbcfg.sessionCircuitKp5',
      ],
      visual: 'icon_grid',
      visualConfig: {
        icons: [
          { label: 'Séries', labelKey: 'onbcfg.labelSeries', color: '#06B6D4' },
          { label: 'Lap', color: '#10B981' },
          { label: 'Superset', color: '#F59E0B' },
          { label: 'EMOM', color: '#EF4444' },
          { label: 'Tabata', color: '#8B5CF6' },
        ],
      },
      features: ['series_circuit', 'lap_circuit', 'superset', 'emom', 'tabata'],
    },
    {
      id: 'session_live',
      badge: 'En direct',
      badgeKey: 'onbcfg.sessionLiveBadge',
      title: 'Suivi en temps réel exercice par exercice',
      titleKey: 'onbcfg.sessionLiveTitle',
      description: "Lance une séance et laisse-toi guider. L'app affiche un exercice à la fois avec le chrono, le nombre de séries, la charge et le temps de repos. Tu vois toujours l'exercice suivant.",
      descriptionKey: 'onbcfg.sessionLiveDesc',
      keyPoints: [
        'Exercice actuel en grand avec toutes ses données',
        'Chrono de repos automatique entre les séries',
        'Modification de la charge ou des reps en direct',
        'FC et courbe cardiaque toujours visibles',
      ],
      keyPointsKeys: [
        'onbcfg.sessionLiveKp1',
        'onbcfg.sessionLiveKp2',
        'onbcfg.sessionLiveKp3',
        'onbcfg.sessionLiveKp4',
      ],
      visual: 'mockup',
      visualConfig: { type: 'live_workout' },
      features: ['live_session', 'rest_timer', 'hr_display'],
    },
    {
      id: 'session_exercises',
      badge: 'Exercices',
      badgeKey: 'onbcfg.sessionExercisesBadge',
      title: "Une bibliothèque d'exercices complète",
      titleKey: 'onbcfg.sessionExercisesTitle',
      description: "Des centaines d'exercices classés par groupe musculaire, disponibles directement. Si un exercice est absent, crée-le en quelques secondes et il sera disponible pour toutes tes séances futures.",
      descriptionKey: 'onbcfg.sessionExercisesDesc',
      keyPoints: [
        'Recherche par nom ou groupe musculaire',
        'Créer un exercice custom en 3 champs',
        'Exercices sauvegardés pour toujours',
        'Poids de corps, machine, haltères, barres',
      ],
      keyPointsKeys: [
        'onbcfg.sessionExercisesKp1',
        'onbcfg.sessionExercisesKp2',
        'onbcfg.sessionExercisesKp3',
        'onbcfg.sessionExercisesKp4',
      ],
      visual: 'icon_grid',
      visualConfig: {
        icons: [
          { label: 'Pectoraux', labelKey: 'onbcfg.iconPectoraux', color: '#EF4444' },
          { label: 'Dos', labelKey: 'onbcfg.iconDos', color: '#3B82F6' },
          { label: 'Jambes', labelKey: 'onbcfg.iconJambes', color: '#10B981' },
          { label: 'Épaules', labelKey: 'onbcfg.iconEpaules', color: '#F59E0B' },
          { label: 'Bras', labelKey: 'onbcfg.iconBras', color: '#8B5CF6' },
          { label: 'Core', color: '#06B6D4' },
        ],
      },
      features: ['exercise_library', 'custom_exercise', 'muscle_groups'],
    },
    {
      id: 'session_summary',
      badge: 'Résumé',
      badgeKey: 'onbcfg.sessionSummaryBadge',
      title: 'Analyse complète après chaque séance',
      titleKey: 'onbcfg.sessionSummaryTitle',
      description: "À la fin de chaque séance, retrouve le volume total soulevé, le nombre de séries complétées, la comparaison avec la séance précédente et les séries qui ont été des records personnels.",
      descriptionKey: 'onbcfg.sessionSummaryDesc',
      keyPoints: [
        'Volume total en kg calculé automatiquement',
        'Comparaison prévu vs réalisé',
        'Record personnel détecté et mis en avant',
        'Courbe FC de la séance complète',
      ],
      keyPointsKeys: [
        'onbcfg.sessionSummaryKp1',
        'onbcfg.sessionSummaryKp2',
        'onbcfg.sessionSummaryKp3',
        'onbcfg.sessionSummaryKp4',
      ],
      visual: 'stats',
      visualConfig: {
        stats: [
          { label: 'Volume', labelKey: 'onbcfg.statVolume', value: 4850, suffix: 'kg', color: '#06B6D4' },
          { label: 'Séries', labelKey: 'onbcfg.labelSeries', value: 32, suffix: '', color: '#10B981' },
          { label: 'PR battus', labelKey: 'onbcfg.statPrBattus', value: 3, suffix: '', color: '#F59E0B' },
        ],
      },
      features: ['session_summary', 'volume_tracking', 'pr_detection'],
    },
  ],
}
